
SERVERS_COUNT = 5
BOX_IMAGE = 'debian/buster64'


Vagrant.configure('2') do |config|

   # Limiter la RAM des VM
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '1000'
    vb.cpus = 2
    vb.gui = false   
  end
  (1..SERVERS_COUNT).each do |i|
    config.vm.define "s#{i}.infra" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "s#{i}.infra"
      subconfig.vm.box_check_update = false
      
      if i == 1
        subconfig.vm.network "private_network", ip: "192.168.50.1"
        subconfig.vm.network 'forwarded_port', guest: 80, host: 80
        subconfig.vm.network 'forwarded_port', guest: 443, host: 443
        
      else
        subconfig.vm.network "private_network", ip: "192.168.50.#{i}"
      
        
      end
      

    end
  end
  config.vm.provision "file", source: "./vagrant", destination: "/vagrant"
  config.vm.provision 'shell', path: 'provision.sh'
end

